[colors.primary]
background = "#0b0c0c"
foreground = "#c2c2c2"

[colors.cursor]
text = "#0b0c0c"
cursor = "#c2c2c2"

[colors.vi_mode_cursor]
text = "#0b0c0c"
cursor = "#c2c2c2"

[colors.search.matches]
foreground = "#0b0c0c"
background = "#c2c2c2"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#566a6a"
background = "#c2c2c2"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0b0c0c"
red = "#5A3C85"
green = "#72648E"
yellow = "#8F7389"
blue = "#9571A4"
magenta = "#9F7CC3"
cyan = "#80899E"
white = "#c2c2c2"

[colors.bright]
black = "#566a6a"
red = "#5A3C85"
green = "#72648E"
yellow = "#8F7389"
blue = "#9571A4"
magenta = "#9F7CC3"
cyan = "#80899E"
white = "#c2c2c2"

[colors.dim]
black = "#c2c2c2"
red = "#5A3C85"
green = "#9F7CC3"
yellow = "#8F7389"
blue = "#9571A4"
magenta = "#72648E"
cyan = "#80899E"
white = "#566a6a"

