# Shell variables
# Generated by 'wal'
wallpaper="/home/lain/Pictures/wallpapers/anime-girl-with-cap-smoking-4k-wallpaper-uhdpaper.com-712@0@j.jpg"

# Special
background='#0b0c0c'
foreground='#c2c2c2'
cursor='#c2c2c2'

# Colors
color0='#0b0c0c'
color1='#5A3C85'
color2='#72648E'
color3='#8F7389'
color4='#9571A4'
color5='#9F7CC3'
color6='#80899E'
color7='#c2c2c2'
color8='#566a6a'
color9='#5A3C85'
color10='#72648E'
color11='#8F7389'
color12='#9571A4'
color13='#9F7CC3'
color14='#80899E'
color15='#c2c2c2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
