--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/lain/Pictures/wallpapers/anime-girl-with-cap-smoking-4k-wallpaper-uhdpaper.com-712@0@j.jpg"

-- Special
background="#0b0c0c"
foreground="#c2c2c2"
cursor="#c2c2c2"

-- Colors
color0="#0b0c0c"
color1="#5A3C85"
color2="#72648E"
color3="#8F7389"
color4="#9571A4"
color5="#9F7CC3"
color6="#80899E"
color7="#c2c2c2"
color8="#566a6a"
color9="#5A3C85"
color10="#72648E"
color11="#8F7389"
color12="#9571A4"
color13="#9F7CC3"
color14="#80899E"
color15="#c2c2c2"
