#! /bin/sh


if ! [ "$( xrandr | grep -Ew "DP-1-... connected" )" == "" ]; then
	xrandr --output DP-1-0.1 --mode 1920x1080 -r 60 --rotation normal --primary
	xrandr --output DP-1-0.2 --mode 1920x1080 -r 60 --rotation normal --left-of DP-1-0.1
	xrandr --output DP-1-0.3 --mode 1920x1080 -r 60 --rotation normal --right-of DP-1-0.1
	xrandr --output eDP-1 --off
#	autorandr -l multimon
	bspc wm -0 '%DP-1-0.2' '%DP-1-0.1' '%DP-1-0.3'
	bspc monitor '%DP-1-0.2' -d I II
	bspc monitor '%DP-1-0.1' -d III IV
	bspc monitor '%DP-1-0.3' -d V VI VII VIII IX X
	sleep 3
	bspc desktop Desktop --remove &
else
	xrandr --output eDP-1
	 --mode 1920x1080 --rotation normal --primary
	bspc monitor -d I II III IV V VI VII VIII IX X

fi
ws-icon-0 = I;一
ws-icon-1 = II;二
ws-icon-2 = III;三
ws-icon-3 = IV;四
ws-icon-4 = V;五
ws-icon-5 = VI;六
ws-icon-6 = VII;七
ws-icon-7 = VIII;八
ws-icon-8 = IX;九
ws-icon-9 = X;十

export SIMPLE_WMS="bspwm"

# execute autostart programs
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x nitrogen > /dev/null || nitrogen --restore
pgrep -x polybar > /dev/null || prime-run polybar &
pgrep -x picom > /dev/null || prime-run picom &

bspc config border_width         2
#bspc config active_border_color \#6200ad
#bspc config normal_border_color \#3a0066
bspc config focused_border_color \#6B6080
bspc config window_gap          30


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config remove_unplugged_monitors	true
bspc config remove_disabled_monitors	true

bscp rule -a nitrogen { floating=on;}
